
# HTML head
head:
  favicon: /favicon/favicon.ico
  high_res_favicon: /favicon/favicon.ico
  apple_touch_icon: /images/icon/icon-72x72.png
  apple_touch_icon_144: /images/icon/icon-144x144.png
  apple_touch_icon_180: /images/icon/icon-180x180.png
  keywords: blog, hexo, mdui

# appbar
appbar:
  title: "Title"
  search: false

index:
  welcome: "Welcome to my blog~"
  notification: false
  gongzhonghao: /images/gh.png
  zsxq: /images/zsxq.png

menu:
  home: /
  archives: /archives
  tags: /tags
  categories: /categories
  github: https://github.com/jiangdequan
  about: /about

# ндуб╫ь╤о
excerpt:
  render: false
  length: 200
  link: Read More

# the url of messages
latest:
  message:
    url: https://raw.githubusercontent.com/jiangdequan/jiangdequan.github.io/message.json

# recent posts count
recent:
  posts: 10

hot:
  tags: 20

# colors of tags(https://www.mdui.org/docs/color)
tags:
  colors:
    - green
    - deep-purple
    - orange
    - teal
    - blue
    - red
    - indigo

# algolia search(https://www.algolia.com/users/sign_in)
algolia:
  applicationID: 'your applicationID'
  apiKey: 'your apiKey'
  adminApiKey: 'your adminApiKey'
  indexName: 'your index name'
  chunkSize: 5000

email: jiangdequan1314@gmail.com
avatar: /images/avatar.png
since_year: 2013

statistics:
  baidu: 28f09eb40c03df56c14ea1736cf3ec3b
  google: UA-127646245-1

rss: /atom.xml
url: https://jiangdequan.github.io/

post:
  alipay: /images/alipay.png
  wechat: /images/wechat.png
